services:
  kafka:
    image: confluentinc/cp-kafka:8.0.2
    container_name: kafka-kraft
    hostname: kafka-kraft
    restart: always
    ports:
      - "9092:9092"   # External access
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      # Listener setup
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka-kraft:29092,CONTROLLER://kafka-kraft:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-kraft:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-kraft:29093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # Basic replication and topic defaults
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # Optional but helpful
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

    volumes:
      - ./.data/kafka:/var/lib/kafka/data

  kafka-cli:
    image: confluentinc/cp-kafka:8.0.2
    container_name: kafka-cli
    depends_on:
      - kafka
    entrypoint: /bin/sh
    tty: true
    networks:
      - default

  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d grpcchat" ]
      interval: 5s
      retries: 5
      timeout: 3s

  redis:
    image: redis:latest
    container_name: redis_cache_no_auth
    ports:
      - "6379:6379"
    restart: unless-stopped

  grpc-server:
    build: ./grpc-server
    container_name: grpc-server
    depends_on:
      kafka:
        condition: service_started
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ./grpc-server/.env
    ports:
      - "50051:50051"

  grpc-client:
    build: ./grpc-client
    container_name: grpc-client
    depends_on:
      - grpc-server
    env_file:
      - ./grpc-client/.env
    ports:
      - "4000:4000"